
IF EXISTS (SELECT * FROM sys.objects WHERE name='cases_Indexed' and type='U')
BEGIN
	DROP TABLE [dbo].[cases_Indexed]
END
GO

CREATE TABLE [cases_Indexed] (
		id	uniqueidentifier,
		casenum	int,
		alt_case_num	varchar(75),
		alt_case_num_2	varchar(75),
		date_of_incident	date,
		date_opened	date,
		close_date	date,
		dormant	bit,
		lim_date	date,
		lim_stat	char(1),
		intake_date	datetime2,
		staffintakeid	uniqueidentifier,
		synopsis	varchar(max),
		docket	varchar(35),
		case_title	varchar(1000),
		special_note	varchar(1000),
		import_date	datetime2,
		matterid	uniqueidentifier,
		classid	uniqueidentifier,
		referredby_namesid	uniqueidentifier,
		referredto_namesid	uniqueidentifier,
		reassign_date	date,
		court_namesid	uniqueidentifier,
		judge_namesid	uniqueidentifier,
		billto_namesid	uniqueidentifier,
		doc_default_path	varchar(255),
		date_created	datetime2,
		staffcreatedid	uniqueidentifier,
		date_modified	datetime2,
		staffmodifiedid	uniqueidentifier,
		requestcaseid	varchar(36),
		cloud_folder_id	varchar(100),
		case_name	varchar(1000),
		is_closed	bit,
		stage	bit,
		marketing_source_id	uniqueidentifier,
		source_info	varchar(500),
		was_read	bit,
		primary_staff_id_computed	uniqueidentifier,
		marketing_campaign_id	uniqueidentifier,
		archived	bit,
		open_status	bit,
		IntakeComment	varchar(max),
		last_update_time	datetime2,
		ledes_client_reference_id	varchar(20),
		matter_phases_id	uniqueidentifier,
		jurisdictionid		uniqueidentifier,
		rulesetid			uniqueidentifier,
		case_folder_name	nvarchar(400),
		onedrivedrivesid	uniqueidentifier,
		document_folder_sync_id	uniqueidentifier,
		lawtoolbox_matterid	int,
		[TableIndex] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [IOC_Clustered_Index_cases_Indexed] PRIMARY KEY CLUSTERED 
(
	[TableIndex] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX IX_NonClustered_Index_cases_Indexed ON [cases_Indexed] (id); 
GO


INSERT INTO [cases_Indexed] (		
		id,
		casenum,
		alt_case_num,
		alt_case_num_2,
		date_of_incident,
		date_opened,
		close_date,
		dormant,
		lim_date,
		lim_stat,
		intake_date,
		staffintakeid,
		synopsis,
		docket,
		case_title,
		special_note,
		import_date,
		matterid,
		classid,
		referredby_namesid,
		referredto_namesid,
		reassign_date,
		court_namesid,
		judge_namesid,
		billto_namesid,
		doc_default_path,
		date_created,
		staffcreatedid,
		date_modified,
		staffmodifiedid,
		requestcaseid,
		cloud_folder_id,
		case_name,
		is_closed,
		stage,
		marketing_source_id,
		source_info,
		was_read,
		primary_staff_id_computed,
		marketing_campaign_id,
		archived,
		open_status,
		IntakeComment,
		last_update_time,
		ledes_client_reference_id,
		matter_phases_id,
		jurisdictionid,
		rulesetid,
		case_folder_name,
		onedrivedrivesid,
		document_folder_sync_id,
		lawtoolbox_matterid
)
SELECT
		id,
		casenum,
		alt_case_num,
		alt_case_num_2,
		date_of_incident,
		date_opened,
		close_date,
		dormant,
		lim_date,
		lim_stat,
		intake_date,
		staffintakeid,
		synopsis,
		docket,
		case_title,
		special_note,
		import_date,
		matterid,
		classid,
		referredby_namesid,
		referredto_namesid,
		reassign_date,
		court_namesid,
		judge_namesid,
		billto_namesid,
		doc_default_path,
		date_created,
		staffcreatedid,
		date_modified,
		staffmodifiedid,
		requestcaseid,
		cloud_folder_id,
		case_name,
		is_closed,
		stage,
		marketing_source_id,
		source_info,
		was_read,
		primary_staff_id_computed,
		marketing_campaign_id,
		archived,
		open_status,
		IntakeComment,
		last_update_time,
		ledes_client_reference_id,
		matter_phases_id,
		jurisdictionid,
		rulesetid,
		case_folder_name,
		onedrivedrivesid,
		document_folder_sync_id,
		lawtoolbox_matterid
FROM [cases]
GO
  
DBCC DBREINDEX('cases_Indexed',' ',90) 
GO

